### ISSUE TITLE
SOLVED: Blank content

### ISSUE THREAD

**Issue by BartGysens** [myTselection/MijnTuin#3]
Thank you to start with (- dank u wel voor deze integratie) !

I installed the integration and logged in but no content appears.
Rebooted, tried again but still no content in the markdown.
Apparently I do not receive a new sensor.

**UPDATE: Solved with release 1.1.2** 

My system:

> Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend-versie: 20230503.3 - latest

Log:
```
Logger: homeassistant.components.sensor
Source: custom_components/mijntuin/utils.py:108
Integration: Sensor (documentation, issues)
First occurred: 14:40:17 (1 occurrences)
Last logged: 14:40:17

Error while setting up mijntuin platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mijntuin/sensor.py", line 79, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/mijntuin/sensor.py", line 43, in dry_setup
    await componentData._force_update()
  File "/config/custom_components/mijntuin/sensor.py", line 113, in _force_update
    self._calendarData = await self._hass.async_add_executor_job(lambda: self._session.getCalendar(calendarlink))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mijntuin/sensor.py", line 113, in <lambda>
    self._calendarData = await self._hass.async_add_executor_job(lambda: self._session.getCalendar(calendarlink))
  File "/config/custom_components/mijntuin/utils.py", line 108, in getCalendar
    response = self.s.get(calendarlink,headers=header,cookies=self.cookies,timeout=10,allow_redirects=False)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
```

**Comment by myTselection** [comment]
Indeed recently I saw the same issue, so solved since 1.1.2.
thanks for the feedback!
